### ISSUE TITLE
My notebook

### ISSUE THREAD

**Issue by zbtong6799** [honda-research-institute/Anomaly-OneVision#2]
English：
1.Modify the dataset file according to the dataset you’re using for training, and be sure to note the file’s path.
2.During training and testing, pay attention to some basic configuration details:
2.1. Since P2P between an RTX 4090 and an H100 differs, you may need to disable it by adding:
bash
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
2.2. Install and configure CUDA.
2.3. Add the CUDA installation path to your environment (e.g. in your PATH or LD_LIBRARY_PATH).
2.4. Watch out for file paths hard-coded in the code—many reflect the author’s own directory structure and must be adjusted.
2.5. Note how many GPUs you have: the author used eight, so adjust both the count and the device indices to match your setup.
2.6. In your terminal, run ip addr show, then use those interface names to set:
bash
export NCCL_SOCKET_IFNAME=<your_interface_name>
3.Create a folder named pretrained_weight. The code will connect to Hugging Face to download some assets. (I used v2rayN-linux-64.AppImage from my download directory to run a paid VPN.)
4.A small personal gripe (not aimed at the author): I find that compatibility and ease of entry for today’s large models are quite poor—especially when you want to adapt them to a very specific task. Even after you’ve read and understood the paper, the hardest part often turns out to be environment setup and related details, which exist only to make the code run and aren’t part of the algorithm’s core. Deep learning feels like it has little interpretable theoretical foundation, yet the frameworks we rely on just keep growing more complex and less compatible.
中文：
1.修改数据集文件，根据训练所使用的数据集进行修改。并注意文件所在的路径
2.训练和测试时，注意一些基础的设置
2.1 4090GPU与H100通信不同，需要进行修改，添加指令：
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
2.2 要配置安装cuda
2.3 expert要添加cuda所在的路径
2.4 要注意代码中文件的路径，很多是根据作者的文件路径修改的
2.5 注意GPU的数量，作者使用了8块，要根据自己的数量和编号进行调整
2.6 终端先运行ip addr show，然后根据结果修改sh文件里面的export NCCL_SOCKET_IFNAME=
3.需要创建一个pretrained_weight文件夹，代码会连接huggingface下载一些东西，我是使用使用download里面的v2rayN-linux-64.AppImage 打开VPN（之前付费买的）
4.个人学习时候的一点小吐槽（不是针对作者），感觉现在的大模型之间的兼容性和入门性比较差，往往你开发一个算法，论文本身即使读懂了，最难的反而是环境配置等因素，而这些往往只是为了支撑你跑通代码，并不是真正的算法核心本身。深度学习，仿佛没有可解释的理论支撑，但所依赖的工具框架却越来越复杂，兼容性越来越差。

**Comment by Eren-yeager-zero** [comment]
> English： 1.Modify the dataset file according to the dataset you’re using for training, and be sure to note the file’s path. 2.During training and testing, pay attention to some basic configuration details: 2.1. Since P2P between an RTX 4090 and an H100 differs, you may need to disable it by adding: bash export NCCL_P2P_DISABLE=1 export NCCL_IB_DISABLE=1 2.2. Install and configure CUDA. 2.3. Add the CUDA installation path to your environment (e.g. in your PATH or LD_LIBRARY_PATH). 2.4. Watch out for file paths hard-coded in the code—many reflect the author’s own directory structure and must be adjusted. 2.5. Note how many GPUs you have: the author used eight, so adjust both the count and the device indices to match your setup. 2.6. In your terminal, run ip addr show, then use those interface names to set: bash export NCCL_SOCKET_IFNAME=<your_interface_name> 3.Create a folder named pretrained_weight. The code will connect to Hugging Face to download some assets. (I used v2rayN-linux-64.AppImage from my download directory to run a paid VPN.) 4.A small personal gripe (not aimed at the author): I find that compatibility and ease of entry for today’s large models are quite poor—especially when you want to adapt them to a very specific task. Even after you’ve read and understood the paper, the hardest part often turns out to be environment setup and related details, which exist only to make the code run and aren’t part of the algorithm’s core. Deep learning feels like it has little interpretable theoretical foundation, yet the frameworks we rely on just keep growing more complex and less compatible. 中文： 1.修改数据集文件，根据训练所使用的数据集进行修改。并注意文件所在的路径 2.训练和测试时，注意一些基础的设置 2.1 4090GPU与H100通信不同，需要进行修改，添加指令： export NCCL_P2P_DISABLE=1 export NCCL_IB_DISABLE=1 2.2 要配置安装cuda 2.3 expert要添加cuda所在的路径 2.4 要注意代码中文件的路径，很多是根据作者的文件路径修改的 2.5 注意GPU的数量，作者使用了8块，要根据自己的数量和编号进行调整 2.6 终端先运行ip addr show，然后根据结果修改sh文件里面的export NCCL_SOCKET_IFNAME= 3.需要创建一个pretrained_weight文件夹，代码会连接huggingface下载一些东西，我是使用使用download里面的v2rayN-linux-64.AppImage 打开VPN（之前付费买的） 4.个人学习时候的一点小吐槽（不是针对作者），感觉现在的大模型之间的兼容性和入门性比较差，往往你开发一个算法，论文本身即使读懂了，最难的反而是环境配置等因素，而这些往往只是为了支撑你跑通代码，并不是真正的算法核心本身。深度学习，仿佛没有可解释的理论支撑，但所依赖的工具框架却越来越复杂，兼容性越来越差。

Hello. Excuse me. May I ask if you encounter something like [rank7]: FileNotFoundError: [Errno 2] No such file or directory when reproducing the code? '/ data / 02 / jiacong/data/anomaly_shapenet screen0 / test / 0026 / views/view_16 PNG' problems? My program always looks for the author's default path, even though I have modified it to my own path in all the files (including.py.sh.json and.yaml).

**Comment by zxyzzz-spec** [comment]
您好，想问下为什么训练用的是siglip，而验证时又是clip
